### ISSUE TITLE
Not sure I'm following guide properly, would appreciate some examples.

### ISSUE THREAD

**Issue by madninjaskillz** [DaveGut/TAPO-Robovac-Dev#1]
Thanks for your research, if I can get this working I'm likely to create a home assistant plugin (and will give full credit where its due)

Having followed your login section, both in postman and c# talking to an RV10, I'm getting :

```
<html><body><center>500 Server Internal Error</center></body></html>
```

Could you confirm that 
* username = email used for tapo?
* email is MD5, hexed then uppercased (not uppercased before hash)
* The Json is literal? ie: ALL of the [ and ] etc are included.

Thanks.

**Comment by DaveGut** [comment]
Username: yes.
email:  yes.  (remember e-mails are case sensitive).
Jason is literal in my working implementation.  Example in groovy using Hubitat's built-in asynchttpPost:


```
def cleanStart() {
	def cmdBody = [method: "setSwitchClean", params: [clean_on: true, clean_mode: 0]]
	asyncSend(cmdBody,"cleanStart", "controlParse")
}
def asyncSend(cmdBody, method, action) {
	def reqParams = [
		uri: "${getDataValue("baseUrl")}/?token=${token}",
		body: cmdBody,
		contentType: "application/json",
		requestContentType: "application/json",
		ignoreSSLIssues: true,
		timeout: 4
	]
	asynchttpPost(action, reqParams, [data: method])
}
```

"action" is the parse method that the platform calls on receipt of a response.

**Comment by madninjaskillz** [comment]
I got there in the end, thanks:

```
{"method":"login","params":{"username":"email@domain.com","password":"7469B***********1A90","hashed":true}}
```
Groovy is being helpful here - as soon as I converted to using models in the c# prototype, it constructed the json properly and everything was happy.

**Comment by DaveGut** [comment]
Closed as answered.
